apiVersion: v1
kind: Service
metadata:
  name: backend-feed-cluster-ip-service
  labels:
    component: backend-feed
spec:
  type: ClusterIP
  selector:
    component: backend-feed
  ports:
    - port: 8080
      targetPort: 8080
