apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-service
spec:
  type: NodePort
  ports:
    - port: 8100
      targetPort: 8100
      nodePort: 31515
  selector:
    component: frontend
