apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reverseproxy
  template:
    metadata:
      labels:
        component: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: codeballet/udacity-reverseproxy
          imagePullPolicy: Always          
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"       
          ports:
            - containerPort: 8080
      restartPolicy: Always
