apiVersion: v1
kind: Service
metadata:
  name: udacity-reverseproxy-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: udacity-reverseproxy
  ports:
    - port: 8080
      targetPort: 8080
